improve java trace output readability
nowsecure/r2frida pull request #317
Opened 2021-05-21 14:21 UTC by apkunpacker

2021-05-21 14:27 UTC, trufae commented on src/agent/index.js
> +          msg += ` backtrace: \n${traceMessage.backtrace.toString().split(",").join("\nat ")}\n`;
```suggestion
          msg += ` backtrace: \n${traceMessage.backtrace.toString().split(',').join('\nat ')}\n`;
```

2021-05-21 14:27 UTC, trufae requested changes

2021-05-21 14:27 UTC, trufae commented on plugins/inject-getpid.js
> +} else
add the missing { } after the else

2021-05-24 15:43 UTC, enovella commented on src/agent/index.js
> +        let msg = `[JAVA TRACE][${traceMessage.timestamp}] ${klass}:${method} - args: ${JSON.stringify(args)}. Return value: ${res.toString()}`;
If you change this to uppercase, make sure you also change other occurrences of `java trace`

2021-05-24 15:46 UTC, apkunpacker commented on src/agent/index.js
> +        let msg = `[JAVA TRACE][${traceMessage.timestamp}] ${klass}:${method} - args: ${JSON.stringify(args)}. Return value: ${res.toString()}`;
yeah sure

2021-05-25 15:07 UTC, trufae reviewed
```js
$ git grep 'java trace'
src/agent/index.js:        let msg = `[java trace][${traceMessage.timestamp}] ${klass}:${method} - args: ${JSON.stringify(args)}. Return value: ${res.toString()}`;
src/agent/index.js:        traceEmit(`[java trace][${timestamp}] Intercept return for ${klass}:${method} with ${value}`);
```

2021-05-25 16:09 UTC, trufae commented
lgtm

2021-05-28 00:53 UTC, trufae commented on plugins/inject-getpid.js
> +
unnecessary empty lines

2021-05-28 00:53 UTC, trufae requested changes
just this little thing

2021-05-28 08:10 UTC, merged